//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{


    public partial class SiteMaster
    {
        /// <summary>
        /// Control phMenuLogueado.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMenuLogueado;
        
        /// <summary>
        /// Control lblUsuarioNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsuarioNombre;
        
        /// <summary>
        /// Control lblUsuarioPuntos.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsuarioPuntos;
        
        /// <summary>
        /// Control phMenuPublico.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMenuPublico;

        /// <summary>
        /// Control MainContent.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
